(* TEST
 setup-ocamlc.byte-build-env;
 script = "touch ${test_build_directory}/test_stop_after.cmo";
 script;

 compiler_output = "compiler-output.raw";
 all_modules = "test_stop_after.ml";
 flags = "-stop-after typing -warn-error +A";
 ocamlc_byte_exit_status = "2";
 ocamlc.byte;

 script = "sh ${test_source_directory}/check-no-deletion.sh";
 script;
*)

let f () =
  (* -warn-error +A will error with unused x below, but that shouldn't cause deleting the
  cmo file, since that weren't generated by us. *)
  let x = 12 in
  1
