(******************************************************************************
 *                                  OxCaml                                    *
 * -------------------------------------------------------------------------- *
 *                               MIT License                                  *
 *                                                                            *
 * Copyright (c) 2026 Jane Street Group LLC                                   *
 * opensource-contacts@janestreet.com                                         *
 *                                                                            *
 * Permission is hereby granted, free of charge, to any person obtaining a    *
 * copy of this software and associated documentation files (the "Software"), *
 * to deal in the Software without restriction, including without limitation  *
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,   *
 * and/or sell copies of the Software, and to permit persons to whom the      *
 * Software is furnished to do so, subject to the following conditions:       *
 *                                                                            *
 * The above copyright notice and this permission notice shall be included    *
 * in all copies or substantial portions of the Software.                     *
 *                                                                            *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR *
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,   *
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL    *
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER *
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING    *
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER        *
 * DEALINGS IN THE SOFTWARE.                                                  *
 ******************************************************************************)

(* Linker script sections for manual EH frame handling, used when using
   dissector with a LLD that lacks 64-bit EH frame support.

   Defines __EH_FRAME_BEGIN__ symbol and provides an empty .eh_frame_hdr
   table. *)
let linker_script_sections =
  ".eh_frame : {\n\
  \    __EH_FRAME_BEGIN__ = .;\n\
  \    *(.eh_frame)\n\
  \    *(.eh_frame.*)\n\
   }\n\
   .eh_frame_hdr : {\n\
  \    /* Empty .eh_frame_hdr - runtime registration handles unwinding */\n\
  \    BYTE(1)                        /* version = 1 */\n\
  \    BYTE(0x1b)                     /* eh_frame_ptr: DW_EH_PE_pcrel|sdata4 */\n\
  \    BYTE(0xff)                     /* fde_count: DW_EH_PE_omit */\n\
  \    BYTE(0xff)                     /* table: DW_EH_PE_omit */\n\
  \    LONG(ADDR(.eh_frame) - .)      /* eh_frame pointer (relative) */\n\
   }\n"

(* C code for manual EH frame registration: uses .init and .fini constructors to
   register/deregister the .eh_frame section at runtime. *)
let c_code =
  {|/* Auto-generated by OxCaml for manual EH frame registration */
extern char __EH_FRAME_BEGIN__[];
extern void __register_frame_info(const void *, void *);
extern void *__deregister_frame_info(const void *);

/* struct object from libgcc - allocate conservatively large buffer */
static char oxcaml_eh_object[128] __attribute__((aligned(8)));

__attribute__((constructor))
static void oxcaml_register_eh_frame(void) {
  __register_frame_info(__EH_FRAME_BEGIN__, oxcaml_eh_object);
}

__attribute__((destructor))
static void oxcaml_deregister_eh_frame(void) {
  __deregister_frame_info(__EH_FRAME_BEGIN__);
}
|}

let generate ~temp_dir =
  let c_file = Filename.concat temp_dir "oxcaml_eh_frame_reg.c" in
  let obj_file = Filename.concat temp_dir "oxcaml_eh_frame_reg.o" in
  let oc = open_out c_file in
  output_string oc c_code;
  close_out oc;
  let exit_code = Ccomp.compile_file ~output:obj_file c_file in
  if exit_code <> 0
  then
    Misc.fatal_errorf
      "Failed to compile EH frame registration file %s (exit code %d)" c_file
      exit_code;
  obj_file
